Add director
Jim5lives/java-filmorate pull request #14
Opened 2024-07-21 15:55 UTC by brnvrn

2024-07-22 12:58 UTC, kostylevv approved these changes
OK!

2024-07-22 17:57 UTC, Jim5lives requested changes

2024-07-22 17:57 UTC, Jim5lives commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        }
нужно убрать эту конструкцию try-catch, она нужна для дебага

2024-07-22 17:57 UTC, Jim5lives commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        }
то же самое, нужно убрать try-catch

2024-07-23 16:13 UTC, Jim5lives approved these changes

2024-07-23 16:31 UTC, merged